const admin = require('firebase-admin');
const path = require('path');

// Firebase Admin SDK の初期化
const serviceAccountPath = path.join(__dirname, '../serviceAccountKey.json');
admin.initializeApp({
  credential: admin.credential.cert(serviceAccountPath),
  databaseURL: 'https://flashcard-95fa7.firebaseio.com',
});

const db = admin.firestore();

async function seedDatabase() {
  try {
    console.log('🗑️  既存データを削除中...');

    // 既存の words を削除
    const wordsSnapshot = await db.collection('words').get();
    const wordsDeletePromises = wordsSnapshot.docs.map(doc => doc.ref.delete());
    await Promise.all(wordsDeletePromises);
    console.log(`✓ ${wordsSnapshot.size} 件の問題を削除しました`);

    // 既存の categories を削除
    const categoriesSnapshot = await db.collection('categories').get();
    const categoriesDeletePromises = categoriesSnapshot.docs.map(doc => doc.ref.delete());
    await Promise.all(categoriesDeletePromises);
    console.log(`✓ ${categoriesSnapshot.size} 件のカテゴリを削除しました`);

    console.log('\n📝 新しいテストデータを挿入中...');

    // カテゴリを作成
    const categoryRef1 = db.collection('categories').doc('category_01');
    await categoryRef1.set({
      name: '中学歴史用語',
      subject: '歴史',
      level: '中学',
      description: '中学歴史の重要用語',
      wordCount: 4,
      createdBy: 'admin',
      createdAt: admin.firestore.Timestamp.now(),
    });
    console.log('✓ カテゴリ: 中学歴史用語');

    const categoryRef2 = db.collection('categories').doc('category_02');
    await categoryRef2.set({
      name: '中学理科',
      subject: '理科',
      level: '中学',
      description: '受験対策：化学・物理・生物・地学分野の重要概念（原子・分子・イオン・化学変化・電流・運動・力・エネルギー・植物・動物・人体・遺伝・進化・大地の変化・天気の変化・地球と宇宙・生態系と人間・身の回りの現象・物質）',
      wordCount: 108,
      createdBy: 'admin',
      createdAt: admin.firestore.Timestamp.now(),
    });
    console.log('✓ カテゴリ: 中学理科');

    // 問題を作成
    const wordsData = [
      {
        categoryId: 'category_01',
        question: '縄文時代とは？',
        answer: '日本の先史時代。打製石器を使用した狩猟採集文化の時代',
        hint: '土器が特徴的な時代',
        examples: ['約16,000年前から約3,000年前', '縄文土器が出現した時代'],
        order: 1,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_01',
        question: '邪馬台国を統治していた女王は？',
        answer: '卑弥呼',
        hint: '弥生時代の日本',
        examples: ['中国の三国志に記録されている', '所在地は諸説ある（近畿説・九州説）'],
        order: 2,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_01',
        question: '645年に中大兄皇子が行った政治改革は？',
        answer: '大化の改新',
        hint: '蘇我氏を倒した',
        examples: ['律令制の基礎が確立', '豪族の権力を制限'],
        order: 3,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_01',
        question: '東大寺の大仏を造立させた天皇は？',
        answer: '聖武天皇',
        hint: '奈良時代の天皇',
        examples: ['749年に退位', '仏教興隆に尽力'],
        order: 4,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      // 中学理科：原子・分子・イオンと化学変化
      {
        categoryId: 'category_02',
        question: '物質をつくる最小単位の粒子を何というか？',
        answer: '原子',
        hint: '元素の基本単位',
        examples: ['水素原子（H）', '酸素原子（O）', '炭素原子（C）'],
        order: 1,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '2個以上の原子が結びついてできた粒子を何というか？',
        answer: '分子',
        hint: '原子が結合したもの',
        examples: ['水分子（H₂O）', '酸素分子（O₂）', '二酸化炭素分子（CO₂）'],
        order: 2,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '原子が電気を帯びた粒子を何というか？',
        answer: 'イオン',
        hint: '電子を失ったり得たりした原子',
        examples: ['ナトリウムイオン（Na⁺）', '塩化物イオン（Cl⁻）'],
        order: 3,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '水（H₂O）を電気分解すると何が発生するか？',
        answer: '水素と酸素',
        hint: '陰極と陽極で気体が発生',
        examples: ['陰極：水素（H₂）', '陽極：酸素（O₂）', '体積比は 2:1'],
        order: 4,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '物質が酸素と結びつく化学変化を何というか？',
        answer: '酸化',
        hint: '燃焼も含まれる',
        examples: ['鉄のさび（Fe → Fe₂O₃）', 'マグネシウムの燃焼（Mg → MgO）'],
        order: 5,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '酸化物から酸素を奪う化学変化を何というか？',
        answer: '還元',
        hint: '酸化の逆',
        examples: ['酸化銅の還元（CuO → Cu）', '製鉄での還元反応'],
        order: 6,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '化学反応の前後で質量は変わらない。この法則を何というか？',
        answer: '質量保存の法則',
        hint: 'フランスの化学者ラボアジエが発見',
        examples: ['密閉容器内での反応', '反応物の質量＝生成物の質量'],
        order: 7,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '化学反応式で、水素と酸素から水ができる反応を表すと？',
        answer: '2H₂ + O₂ → 2H₂O',
        hint: '水素分子と酸素分子から水分子',
        examples: ['原子の数が左右で等しい', '係数で調整する'],
        order: 8,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '化学式で食塩（塩化ナトリウム）を表すと？',
        answer: 'NaCl',
        hint: 'ナトリウムイオンと塩化物イオン',
        examples: ['Na⁺ と Cl⁻ のイオン結合', '水に溶けやすい'],
        order: 9,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '陽イオンと陰イオンが結びついた化合物を何というか？',
        answer: 'イオン化合物',
        hint: '電気的引力で結合',
        examples: ['食塩（NaCl）', '酸化マグネシウム（MgO）'],
        order: 10,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '炭酸水素ナトリウム（重曹）を加熱すると何が発生するか？',
        answer: '二酸化炭素（CO₂）',
        hint: '熱分解の反応',
        examples: ['2NaHCO₃ → Na₂CO₃ + H₂O + CO₂', '炭酸ナトリウムと水も生成'],
        order: 11,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '銅を空気中で加熱すると表面が黒くなる。この黒い物質は？',
        answer: '酸化銅（CuO）',
        hint: '銅の酸化物',
        examples: ['2Cu + O₂ → 2CuO', '質量は増加する'],
        order: 12,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      // 電流・回路
      {
        categoryId: 'category_02',
        question: '電流、電圧、抵抗の関係を表す法則を何というか？',
        answer: 'オームの法則',
        hint: 'V = I × R',
        examples: ['電圧（V） = 電流（I） × 抵抗（R）', '電流 = 電圧 ÷ 抵抗'],
        order: 13,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '直列回路では、各抵抗を流れる電流はどうなるか？',
        answer: 'すべて等しい（同じ）',
        hint: '1本の道を流れる電流',
        examples: ['I₁ = I₂ = I₃', '抵抗の和：R = R₁ + R₂ + R₃'],
        order: 14,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '並列回路では、各抵抗にかかる電圧はどうなるか？',
        answer: 'すべて等しい（同じ）',
        hint: '枝分かれした回路',
        examples: ['V₁ = V₂ = V₃', '電流の和：I = I₁ + I₂ + I₃'],
        order: 15,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '電力を求める公式は？（電圧と電流を使う場合）',
        answer: '電力（W） = 電圧（V） × 電流（I）',
        hint: 'P = V × I',
        examples: ['単位はワット（W）', '100V × 2A = 200W'],
        order: 16,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      // 運動と力
      {
        categoryId: 'category_02',
        question: '物体に力がはたらかないか、はたらいてもつり合っているとき、静止している物体は静止し続け、運動している物体は等速直線運動を続ける。この法則を何というか？',
        answer: '慣性の法則（ニュートンの第一法則）',
        hint: '物体の性質',
        examples: ['電車が急ブレーキで体が前に傾く', '静止した物体は動き出さない'],
        order: 17,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '物体Aが物体Bに力を加えると、物体Bも物体Aに同じ大きさで逆向きの力を加える。この法則を何というか？',
        answer: '作用・反作用の法則（ニュートンの第三法則）',
        hint: '2つの物体間の力',
        examples: ['壁を押すと壁から押し返される', 'ロケットの推進力'],
        order: 18,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '速さ（m/s）を求める公式は？',
        answer: '速さ = 移動距離 ÷ 時間',
        hint: 'v = s ÷ t',
        examples: ['100m を 10秒 = 10 m/s', '単位はメートル毎秒（m/s）'],
        order: 19,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '物体の運動の速さや向きを変える原因となるものは何か？',
        answer: '力',
        hint: '押したり引いたり',
        examples: ['重力', '摩擦力', '弾性力', '磁力'],
        order: 20,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      // エネルギー
      {
        categoryId: 'category_02',
        question: '物理における「仕事」の定義と公式は？',
        answer: '仕事（J） = 力（N） × 力の向きに移動した距離（m）',
        hint: 'W = F × s',
        examples: ['単位はジュール（J）', '10N の力で 5m 押す = 50J'],
        order: 21,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '単位時間あたりにする仕事の量を何というか？',
        answer: '仕事率',
        hint: 'P = W ÷ t',
        examples: ['単位はワット（W）', '100J の仕事を 2秒 = 50W'],
        order: 22,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '高い所にある物体がもつエネルギーを何というか？',
        answer: '位置エネルギー',
        hint: '重力によるエネルギー',
        examples: ['質量が大きいほど大きい', '高さが高いほど大きい'],
        order: 23,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '運動している物体がもつエネルギーを何というか？',
        answer: '運動エネルギー',
        hint: '速さに関係するエネルギー',
        examples: ['質量が大きいほど大きい', '速さが速いほど大きい', '速さの2乗に比例'],
        order: 24,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      // 植物・動物
      {
        categoryId: 'category_02',
        question: '植物が光を利用して、二酸化炭素と水からデンプンなどの養分をつくる働きを何というか？',
        answer: '光合成',
        hint: '葉緑体で行われる',
        examples: ['6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂', '酸素が発生する', '光エネルギーを化学エネルギーに変換'],
        order: 25,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '植物が根から吸収した水が葉の気孔から水蒸気として出ていく現象を何というか？',
        answer: '蒸散',
        hint: '水分が蒸発して出ていく',
        examples: ['気孔から行われる', '根からの水の吸い上げに関係', '葉の裏側に多い'],
        order: 26,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '種子が胚珠に包まれている植物を何というか？',
        answer: '被子植物',
        hint: '子房がある',
        examples: ['サクラ', 'アブラナ', 'ツツジ', '子房が果実になる'],
        order: 27,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '胚珠がむき出しになっている植物を何というか？',
        answer: '裸子植物',
        hint: '子房がない',
        examples: ['マツ', 'スギ', 'イチョウ', '花びらがない'],
        order: 28,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '背骨（脊椎）をもつ動物を何というか？',
        answer: '脊椎動物',
        hint: '背骨がある動物',
        examples: ['魚類', '両生類', '爬虫類', '鳥類', '哺乳類'],
        order: 29,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '背骨をもたない動物を何というか？',
        answer: '無脊椎動物',
        hint: '背骨がない動物',
        examples: ['節足動物（昆虫、甲殻類）', '軟体動物（貝類、イカ）', 'その他'],
        order: 30,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '子が親と同じ特徴を受け継ぐことを何というか？',
        answer: '遺伝',
        hint: '形質の伝わり',
        examples: ['メンデルの法則', '優性の法則', '分離の法則'],
        order: 31,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '生物の体をつくる基本単位を何というか？',
        answer: '細胞',
        hint: '顕微鏡で見える小さな部屋',
        examples: ['細胞膜', '細胞質', '核', '植物細胞には細胞壁と葉緑体'],
        order: 32,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '細胞が2つに分かれて増えることを何というか？',
        answer: '細胞分裂',
        hint: '1つの細胞が2つになる',
        examples: ['核が先に分裂', '染色体が見られる', '成長や生殖に関係'],
        order: 33,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '生物が養分を分解して、生命活動に必要なエネルギーを取り出すことを何というか？',
        answer: '呼吸',
        hint: '酸素を使って養分を分解',
        examples: ['C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O', '二酸化炭素が発生', 'ミトコンドリアで行われる'],
        order: 34,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '変温動物である脊椎動物2つのグループは？',
        answer: '魚類と両生類',
        hint: '体温が外界の温度によって変わる',
        examples: ['魚類：えらで呼吸、水中生活', '両生類：幼生はえら、成体は肺、水中と陸上'],
        order: 35,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '恒温動物である脊椎動物2つのグループは？',
        answer: '鳥類と哺乳類',
        hint: '体温を一定に保つことができる',
        examples: ['鳥類：羽毛、卵生', '哺乳類：体毛、胎生（一部卵生）'],
        order: 36,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      // 人体
      {
        categoryId: 'category_02',
        question: '口から入った食物が最初に消化酵素で分解される養分は何か？',
        answer: 'デンプン',
        hint: 'だ液に含まれる酵素',
        examples: ['だ液アミラーゼ（唾液）', 'デンプン → 麦芽糖', '口の中で分解が始まる'],
        order: 37,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '小腸の壁にある、養分の吸収面積を広げるための突起を何というか？',
        answer: '柔毛（じゅうもう）',
        hint: '小腸の内壁の小さな突起',
        examples: ['毛細血管が通っている', '表面積を大きくする', '栄養素を効率的に吸収'],
        order: 38,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '酸素を多く含む血液（動脈血）を全身に送り出す心臓の部屋はどこか？',
        answer: '左心室',
        hint: '心臓の4つの部屋のうち',
        examples: ['最も筋肉が厚い', '大動脈につながる', '全身に血液を送る'],
        order: 39,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '血液中で酸素を運ぶ赤い色素を含む血球は何か？',
        answer: '赤血球',
        hint: 'ヘモグロビンを含む',
        examples: ['酸素と結びつく', '核がない', '赤い色はヘモグロビンによる'],
        order: 40,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '刺激を受け取って、脳や脊髄に信号を伝える神経を何というか？',
        answer: '感覚神経',
        hint: '受容器から中枢へ',
        examples: ['目、耳、皮膚などから脳へ', '求心性神経ともいう'],
        order: 41,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '脳や脊髄からの命令を筋肉などに伝える神経を何というか？',
        answer: '運動神経',
        hint: '中枢から効果器へ',
        examples: ['脳から筋肉へ命令', '遠心性神経ともいう'],
        order: 42,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      // 生物の増え方と遺伝
      {
        categoryId: 'category_02',
        question: '雌雄の生殖細胞が合体して新しい個体をつくる生殖の方法を何というか？',
        answer: '有性生殖',
        hint: '受精が必要',
        examples: ['精子と卵が合体', '遺伝子の組み合わせが変わる', '変異が生まれやすい'],
        order: 43,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '生殖細胞を使わず、体の一部から新しい個体をつくる生殖の方法を何というか？',
        answer: '無性生殖',
        hint: '受精がない',
        examples: ['分裂、出芽、栄養生殖', '親と同じ遺伝子', 'ジャガイモの芽から増える'],
        order: 44,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '生殖細胞ができるとき、染色体の数が半分になる特別な細胞分裂を何というか？',
        answer: '減数分裂',
        hint: '体細胞分裂とは異なる',
        examples: ['染色体数が半分になる', '精子や卵ができる', '受精で元の数に戻る'],
        order: 45,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '遺伝子の本体である、細胞の核に含まれる物質は何か？',
        answer: 'DNA（デオキシリボ核酸）',
        hint: '二重らせん構造',
        examples: ['遺伝情報を保存', '塩基の配列が遺伝暗号', 'A、T、G、Cの4種類の塩基'],
        order: 46,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      // 進化
      {
        categoryId: 'category_02',
        question: '長い年月をかけて生物の種類が変化していくことを何というか？',
        answer: '進化',
        hint: '生物の変遷',
        examples: ['ダーウィンの進化論', '化石による証拠', '自然選択'],
        order: 47,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '起源が同じで、はたらきは異なるが基本的な骨格が似ている器官を何というか？',
        answer: '相同器官',
        hint: '進化の証拠の一つ',
        examples: ['ヒトの腕、クジラのひれ、コウモリの翼', '骨格の配置が共通', '共通の祖先から進化'],
        order: 48,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      // 大地の変化
      {
        categoryId: 'category_02',
        question: '地球内部で地震が発生した場所を何というか？',
        answer: '震源',
        hint: '地下で最初に揺れが始まる場所',
        examples: ['震源の真上が震央', '深さによって浅発地震・深発地震', '震源から波が伝わる'],
        order: 49,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '地震のとき最初に到達する小さな揺れを何というか？',
        answer: '初期微動（P波）',
        hint: '速く伝わる波',
        examples: ['Primary wave（第一波）', '縦波', 'S波より速い'],
        order: 50,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '初期微動に続く大きな揺れを何というか？',
        answer: '主要動（S波）',
        hint: '遅く伝わる大きな波',
        examples: ['Secondary wave（第二波）', '横波', 'P波より遅い'],
        order: 51,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: 'マグマが冷えて固まってできた岩石を何というか？',
        answer: '火成岩',
        hint: 'マグマや溶岩が起源',
        examples: ['火山岩（急冷）：斑状組織', '深成岩（徐冷）：等粒状組織', '花こう岩、玄武岩など'],
        order: 52,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '地表で砂や泥が積もって固まってできた岩石を何というか？',
        answer: '堆積岩',
        hint: '層になって積もる',
        examples: ['れき岩、砂岩、泥岩', '化石が含まれることがある', '地層をつくる'],
        order: 53,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '地層が堆積した当時の環境を知る手がかりとなる化石を何というか？',
        answer: '示相化石',
        hint: '環境を示す化石',
        examples: ['サンゴ：暖かく浅い海', 'ブナ：冷涼な気候', 'シジミ：汽水域'],
        order: 54,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '地層が堆積した年代を知る手がかりとなる化石を何というか？',
        answer: '示準化石',
        hint: '年代を示す化石',
        examples: ['アンモナイト：中生代', '三葉虫：古生代', '短期間に広範囲に生息'],
        order: 55,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      // 天気の変化
      {
        categoryId: 'category_02',
        question: '空気中に含まれる水蒸気の割合を何というか？',
        answer: '湿度',
        hint: '％で表す',
        examples: ['湿度 = （水蒸気量 ÷ 飽和水蒸気量）× 100', '100％で飽和', '湿度が高いとじめじめ'],
        order: 56,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '空気が冷やされて水蒸気が水滴に変わり始める温度を何というか？',
        answer: '露点',
        hint: '飽和に達する温度',
        examples: ['気温が露点に達すると結露', '夜露や霧ができる', '雲ができる'],
        order: 57,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '性質の異なる2つの気団がぶつかる境界面を何というか？',
        answer: '前線',
        hint: '寒気と暖気の境界',
        examples: ['温暖前線', '寒冷前線', '停滞前線', '閉塞前線'],
        order: 58,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '暖気が寒気の上にはい上がってできる前線を何というか？',
        answer: '温暖前線',
        hint: '暖気が主役',
        examples: ['なだらかに上昇', '広範囲に長時間の雨', '乱層雲ができる'],
        order: 59,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '寒気が暖気の下に潜り込んでできる前線を何というか？',
        answer: '寒冷前線',
        hint: '寒気が主役',
        examples: ['急激に上昇', '狭い範囲に短時間の強い雨', '積乱雲ができる'],
        order: 60,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },      // 地球と宇宙
      {
        categoryId: 'category_02',
        question: '地球が自分の軸を中心に1回転することを何というか？',
        answer: '自転',
        hint: '1日で1回転',
        examples: ['約24時間で1回転', '昼と夜ができる', '西から東へ回転'],
        order: 61,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '地球が太陽のまわりを1周することを何というか？',
        answer: '公転',
        hint: '1年で1周',
        examples: ['約365日で1周', '季節の変化が起こる', '地軸が傾いている'],
        order: 62,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '太陽系の8つの惑星のうち、地球より太陽に近い惑星2つは？',
        answer: '水星と金星',
        hint: '内惑星',
        examples: ['水星：最も太陽に近い', '金星：地球の内側で最も明るい', '地球型惑星（岩石でできている）'],
        order: 63,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '月が太陽の光を受けて、形が変わって見える現象を何というか？',
        answer: '月の満ち欠け',
        hint: '約1ヶ月の周期',
        examples: ['新月→三日月→上弦の月→満月→下弦の月→新月', '約29.5日の周期', '月は自ら光らない'],
        order: 64,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '太陽が月によって隠される現象を何というか？',
        answer: '日食',
        hint: '太陽・月・地球の順',
        examples: ['太陽−月−地球の順に並ぶ', '皆既日食と部分日食', '新月のときに起こる'],
        order: 65,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '月が地球の影に入って暗くなる現象を何というか？',
        answer: '月食',
        hint: '太陽・地球・月の順',
        examples: ['太陽−地球−月の順に並ぶ', '皆既月食と部分月食', '満月のときに起こる'],
        order: 66,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      // 生態系と人間
      {
        categoryId: 'category_02',
        question: '生物どうしの食べる・食べられるの関係を何というか？',
        answer: '食物連鎖',
        hint: '栄養のつながり',
        examples: ['植物→草食動物→肉食動物', 'エネルギーの流れ', '生産者→消費者'],
        order: 67,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '光合成によって有機物をつくり出す生物を何というか？',
        answer: '生産者',
        hint: '栄養をつくる',
        examples: ['植物', '植物プランクトン', '光合成を行う'],
        order: 68,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '他の生物を食べて栄養を得る生物を何というか？',
        answer: '消費者',
        hint: '栄養を利用する',
        examples: ['動物', '草食動物・肉食動物', '他の生物を食べる'],
        order: 69,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '生物の遺骸や排出物を無機物に分解する生物を何というか？',
        answer: '分解者',
        hint: '有機物を分解する',
        examples: ['菌類（カビ、キノコ）', '細菌類', '土に返す役割'],
        order: 70,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '人間の活動によって大気中の二酸化炭素が増加し、地球の平均気温が上昇する現象を何というか？',
        answer: '地球温暖化',
        hint: '温室効果ガスの増加',
        examples: ['化石燃料の燃焼', '海面上昇', '異常気象の増加'],
        order: 71,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '元々その地域にいなかった生物が、人間の活動によって持ち込まれた生物を何というか？',
        answer: '外来生物（外来種）',
        hint: '本来の生息地ではない',
        examples: ['在来種を脅かす', 'アライグマ、ブラックバス', '生態系のバランスを崩す'],
        order: 72,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      // 身の回りの現象・物質
      {
        categoryId: 'category_02',
        question: '光が物体の表面で跳ね返る現象を何というか？',
        answer: '反射',
        hint: '鏡で光が跳ね返る',
        examples: ['入射角＝反射角', '鏡の法則', '正反射と乱反射'],
        order: 73,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '光が異なる物質に進むときに、境界面で曲がる現象を何というか？',
        answer: '屈折',
        hint: '水中の物が曲がって見える',
        examples: ['空気から水に入ると屈折', 'レンズの原理', '光の速さの違いで起こる'],
        order: 74,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '凸レンズで平行な光が1点に集まる点を何というか？',
        answer: '焦点',
        hint: 'レンズの中心からの距離が焦点距離',
        examples: ['焦点距離が短いほど屈折が大きい', '焦点を通る光は平行に進む', '実像と虚像'],
        order: 75,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '音が1秒間に振動する回数を何というか？',
        answer: '振動数（周波数）',
        hint: '単位はヘルツ（Hz）',
        examples: ['振動数が大きいほど高い音', '人間は20～20,000Hz', '440Hzは「ラ」の音'],
        order: 76,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '物質が液体から気体に変わる現象を何というか？',
        answer: '蒸発（気化）',
        hint: '水が水蒸気になる',
        examples: ['沸点で激しく起こる（沸騰）', '表面から起こる', '蒸発すると温度が下がる'],
        order: 77,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '物質が気体から液体に変わる現象を何というか？',
        answer: '凝縮（液化）',
        hint: '水蒸気が水になる',
        examples: ['冷やすと液体になる', 'コップの表面に水滴', '雲ができる'],
        order: 78,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '物質が固体から液体に変わるときの温度を何というか？',
        answer: '融点',
        hint: '氷が水になる温度',
        examples: ['水の融点は0℃', '純物質は一定の温度', '状態変化中は温度が変わらない'],
        order: 79,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '物質が液体から気体に変わるときの温度を何というか？',
        answer: '沸点',
        hint: '水が水蒸気になる温度',
        examples: ['水の沸点は100℃（1気圧）', '純物質は一定の温度', '圧力が高いと沸点は上がる'],
        order: 80,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '水に溶けている物質を何というか？',
        answer: '溶質',
        hint: '溶かされているもの',
        examples: ['食塩水の食塩', '砂糖水の砂糖', '溶媒に溶ける'],
        order: 81,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '物質を溶かしている液体を何というか？',
        answer: '溶媒',
        hint: '溶かしているもの',
        examples: ['食塩水の水', '溶質を溶かす', '水溶液では水が溶媒'],
        order: 82,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '一定量の溶媒に溶ける溶質の最大量を何というか？',
        answer: '溶解度',
        hint: '温度によって変わる',
        examples: ['水100gに溶ける物質の質量（g）', '温度が高いほど多く溶ける（気体は例外）', '溶解度曲線'],
        order: 83,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '水溶液100gに溶けている溶質の質量の割合を何というか？',
        answer: '質量パーセント濃度',
        hint: '（溶質の質量÷溶液の質量）×100',
        examples: ['単位は%', '10gの食塩を90gの水に溶かすと10%', '溶質÷（溶質＋溶媒）×100'],
        order: 84,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      // 酸・アルカリと中和
      {
        categoryId: 'category_02',
        question: '青色リトマス紙を赤く変える性質を何というか？',
        answer: '酸性',
        hint: '酸っぱい味',
        examples: ['塑酸、レモン汁', 'pHが7より小さい', '水素イオン（H⁺）を生じる'],
        order: 85,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '赤色リトマス紙を青く変える性質を何というか？',
        answer: 'アルカリ性',
        hint: '苦い味、ぬるぬるする',
        examples: ['石けん水、水酸化ナトリウム', 'pHが7より大きい', '水酸化物イオン（OH⁻）を生じる'],
        order: 86,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '溶液の酸性・アルカリ性の強さを表す指標を何というか？',
        answer: 'pH（ピーエッチ、ペーハー）',
        hint: '0～14の目盛り',
        examples: ['pH7が中性', 'pH7未満が酸性', 'pH7より大がアルカリ性'],
        order: 87,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '酸とアルカリが反応して、お互いの性質を打ち消し合う反応を何というか？',
        answer: '中和',
        hint: '酸性＋アルカリ性→塩＋水',
        examples: ['塩酸＋水酸化ナトリウム→食塩＋水', 'H⁺ + OH⁻ → H₂O', '熱が発生する'],
        order: 88,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '酸性やアルカリ性を調べるときに使う色が変わる薬品を何というか？',
        answer: '指示薬',
        hint: 'pHによって色が変わる',
        examples: ['リトマス紙（青・赤）', 'BTB溶液（黄・緑・青）', 'フェノールフタレイン（無色・赤）'],
        order: 89,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '中和反応でできる物質のうち、酸とアルカリからできる物質を何というか？',
        answer: '塩',
        hint: '水と一緒に生成',
        examples: ['食塩（塩化ナトリウム）', '塁酸カリウム', '中和で水と同時にできる'],
        order: 90,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      // 磁界と電磁誘導
      {
        categoryId: 'category_02',
        question: '磁石や電流のまわりにできる、磁力が働く空間を何というか？',
        answer: '磁界',
        hint: '磁石の周りの空間',
        examples: ['磁力線で表す', 'N極から出てS極に入る', '方位磁針が向く'],
        order: 91,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '磁界の向きや様子を表す線を何というか？',
        answer: '磁力線',
        hint: 'N極からS極へ',
        examples: ['磁力線が密なほど磁界が強い', '交わらない', '閉じた曲線'],
        order: 92,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '電流が流れる導線のまわりにできる磁界の向きを調べる法則は？',
        answer: '右ねじの法則（右手の法則）',
        hint: '親指が電流の向き',
        examples: ['右手の親指を電流の向きに向ける', '他の4本の指が磁界の向き', 'コイルでは中心がN極かS極か'],
        order: 93,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: 'コイルの中の磁石を動かすと、コイルに電流が流れる現象を何というか？',
        answer: '電磁誘導',
        hint: '磁界が変化すると電流が生じる',
        examples: ['ファラデーが発見', '発電機の原理', '磁石を動かす速さが速いほど大きな電流'],
        order: 94,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '電流が流れるコイルを磁石の間に置くと回転する装置を何というか？',
        answer: 'モーター（電動機）',
        hint: '電気エネルギーを運動エネルギーに変換',
        examples: ['フレミングの左手の法則', '電流の向きを変えると回転方向が逆', '扇風機、洗濯機などに利用'],
        order: 95,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '電磁誘導を利用して、運動エネルギーを電気エネルギーに変える装置を何というか？',
        answer: '発電機',
        hint: 'コイルを回転させる',
        examples: ['水力発電、火力発電', 'タービンでコイルを回す', '自転車のライト'],
        order: 96,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      // 排出系と反射
      {
        categoryId: 'category_02',
        question: '血液中の老廃物をこし取って尿をつくる器官を何というか？',
        answer: 'じん臓（腔臓）',
        hint: 'そら豆の形',
        examples: ['血液をろ過', '尿素を排出', '一対（2個）'],
        order: 97,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: 'たんぱく質が分解されてできる有害な物質で、肃によって水に溶ける尿素に変えられる物質は？',
        answer: 'アンモニア',
        hint: '刺激臭のある気体',
        examples: ['たんぱく質の分解物', '肌で尿素に変換', '有毒なので排出が必要'],
        order: 98,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '刺激を受けてから、脳を経由せずにせき髄で命令が出されて起こる無意識の反応を何というか？',
        answer: 'せき髄反射（反射）',
        hint: '無意識の素早い反応',
        examples: ['熟い物に触れて手を引っ込める', '膝を叩くと脚が伸びる', '脳より速い反応'],
        order: 99,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '刺激→感覚器官→感覚神経→せき髄→運動神経→筋肉という経路で起こる反射の例は？',
        answer: '熟い物に触れて手を引っ込める',
        hint: '脳を通らない',
        examples: ['膝蛋反射', '危険から身を守る', '無意識に起こる'],
        order: 100,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      // 日本の天気・台風・火山
      {
        categoryId: 'category_02',
        question: '大気圧が周囲より高いところを何というか？',
        answer: '高気圧',
        hint: '中心から外へ風が吹く',
        examples: ['下降気流で雲ができにくい', '晴天になりやすい', '北半球では時計回りに風が吹く'],
        order: 101,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '大気圧が周囲より低いところを何というか？',
        answer: '低気圧',
        hint: '外から中心へ風が吹き込む',
        examples: ['上昇気流で雲ができやすい', '曇りや雨になりやすい', '北半球では反時計回りに風が吹く'],
        order: 102,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '夏に太平洋から日本に吹く湿った南東の風を何というか？',
        answer: '夏の季節風（南東の季節風）',
        hint: '太平洋高気圧から',
        examples: ['湿度が高い', '梅雨をもたらす', '暑い天気'],
        order: 103,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '冬にシベリアから日本に吹く乾燥した北西の風を何というか？',
        answer: '冬の季節風（北西の季節風）',
        hint: 'シベリア高気圧から',
        examples: ['日本海側に大雪', '太平洋側は乾燥', '寒い天気'],
        order: 104,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '熱帯の海上で発生する、中心付近の風速が毎秒17m以上の熱帯低気圧を何というか？',
        answer: '台風',
        hint: '夏から秋に日本に接近',
        examples: ['反時計回りに渦巻く', '強風と大雨', '目の部分は穏やか'],
        order: 105,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: '地下のマグマが地表に噪出する現象を何というか？',
        answer: '火山の噪火',
        hint: 'マグマが地表に出る',
        examples: ['溶岩、火山ガス、火山灰', '富士山、桜島など', '噴火と噴石'],
        order: 106,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: 'マグマに含まれる二酸化けい素の量が多いマグマの特徴は？',
        answer: '粘り気が大きく、白っぽい色',
        hint: '流れにくい',
        examples: ['爆発的な噪火', '有珠山、雲仙岳', '火山灰が多い'],
        order: 107,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
      {
        categoryId: 'category_02',
        question: 'マグマに含まれる二酸化けい素の量が少ないマグマの特徴は？',
        answer: '粘り気が小さく、黒っぽい色',
        hint: '流れやすい',
        examples: ['穏やかな噪火', 'ハワイの火山', '溶岩が遠くまで流れる'],
        order: 108,
        createdBy: 'admin',
        createdAt: admin.firestore.Timestamp.now(),
      },
    ];

    for (const word of wordsData) {
      const wordRef = db.collection('words').doc();
      await wordRef.set(word);
      console.log(`✓ 問題追加: ${word.question}`);
    }

    console.log('\n✅ すべてのテストデータが正常に挿入されました！');
    process.exit(0);
  } catch (error) {
    console.error('❌ エラーが発生しました:', error);
    process.exit(1);
  }
}

seedDatabase();
